### ISSUE TITLE
LuckPerms extension fails to register

### ISSUE THREAD

**Issue by fort-bean** [plan-player-analytics/Plan#1266]
### Describe the issue
LuckPerms extension throws exception in console after upgrading plugins and server to 1.15.1.

### Server information

**Plan Version:** 5.0 build 335
**Server Type**: Ubuntu Server 18.04.3 LTS
**Server:** Paper 1.15.1-R0.1-SNAPSHOT (git-Paper-29 (MC: 1.15.1))
**Database:** MySQL
**Plugins:** LuckPerms 4.4.1, Dynmap v3.0-beta-9-250

**Operating SubSystem:** Linux (amd64) version 4.15.0-72-generic
**Java Version:** 1.8.0_232, Private Build
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.232-b09, Private Build

### Benchmarks
```
975 ms     -55 MB  Enable
```

### Exceptions & Other Logs
[16:12:21] [Plan Reload Thread/WARN]: [Plan] One or more extensions failed to register, see suppressed exceptions (They can be disabled in Plan config).
[16:12:21] [Plan Reload Thread/WARN]: [Plan] Error was caught by com.djrapitops.plan.extension.ExtensionService
java.lang.IllegalStateException: One or more extensions failed to register:
        Suppressed: java.lang.IllegalStateException: LuckPermsExtensionFactory failed to create Extension
        Caused by: java.lang.NoClassDefFoundError: net/luckperms/api/model/user/User
        Caused by: java.lang.ClassNotFoundException: net.luckperms.api.model.user.User
[16:12:21] [Plan Reload Thread/INFO]: [Plan] Player Analytics Enabled. (691 ms)

### Additional information
Integration worked fine with previous releases of PaperMC build 237 (MC 1.14.4), LuckPerms-Bukkit-4.4.27 and Plan 5.0 build 260. Recently added a second server reporting into the same SQL database, has an identical environment but uses OpenJDK v11 instead of v8. Webserver is only enabled on the original host which is running v8, and both servers are reporting the same issue in the logs.

**Comment by Rsl1122** [comment]
This is because their API was updated

Update Luckperms to v5
https://luckperms.net/
or
Disable the integration in the Plan config

**Comment by Rsl1122** [comment]
Same as #1248

**Comment by fort-bean** [comment]
A thousand apologies. I obtained the plugin from the SpigotMC site which isn't updated, once I got the latest version from luckperms.net everything is happy again.

**Comment by Rsl1122** [comment]
I'll pin this as people will likely report this again until luck puts newest version on spigot
