### ISSUE TITLE
Build 361 causes Immersive Engineering crash

### ISSUE THREAD

**Issue by database64128** [plan-player-analytics/Plan#1292]
### Describe the issue

After updating Plan from 335 to 361, when the server finishes starting, Immersive Engineering throws an exception and crashes the server. Rolling back to build 335 fixed the issue.

### Server information

Forge 2847
I tested with SpongeForge 7.1.9 RC3984, 7.1.8, and 7.1.7 RC 3928. The issue occurs on all these versions.

### Exceptions & Other Logs

```
[15:54:30] [Server thread/INFO] [immersiveengineering]: WorldData loading
[15:54:30] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)

Caused by: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/energy/wires/IICProxy
	at blusunrize.immersiveengineering.common.IESaveData.readFromNBT(IESaveData.java:59) ~[IESaveData.class:?]
	at net.minecraft.world.storage.MapStorage.getOrLoadData(SourceFile:52) ~[bfm.class:?]
	at net.minecraft.world.World.loadData(World.java:3682) ~[amu.class:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.serverStarted(ImmersiveEngineering.java:206) ~[ImmersiveEngineering.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.energy.wires.IICProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at blusunrize.immersiveengineering.common.IESaveData.readFromNBT(IESaveData.java:59) ~[IESaveData.class:?]
	at net.minecraft.world.storage.MapStorage.getOrLoadData(SourceFile:52) ~[bfm.class:?]
	at net.minecraft.world.World.loadData(World.java:3682) ~[amu.class:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.serverStarted(ImmersiveEngineering.java:206) ~[ImmersiveEngineering.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_232]
Caused by: java.lang.SecurityException: class "blusunrize.immersiveengineering.api.energy.wires.IICProxy"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_232]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_232]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_232]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_232]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at blusunrize.immersiveengineering.common.IESaveData.readFromNBT(IESaveData.java:59) ~[IESaveData.class:?]
	at net.minecraft.world.storage.MapStorage.getOrLoadData(SourceFile:52) ~[bfm.class:?]
	at net.minecraft.world.World.loadData(World.java:3682) ~[amu.class:?]
	at blusunrize.immersiveengineering.ImmersiveEngineering.serverStarted(ImmersiveEngineering.java:206) ~[ImmersiveEngineering.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_232]
[15:54:30] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify sun.reflect.GeneratedMethodAccessor10 (untransformed name: sun.reflect.GeneratedMethodAccessor10)
[15:54:30] [Server thread/INFO] [STDOUT]: [net.minecraft.crash.CrashReport:func_85057_a:300]: Negative index in crash report handler (0/5)
[15:54:30] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /srv/cube_inc/./crash-reports/crash-2020-01-16_15.54.30-server.txt
[15:54:30] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[15:54:30] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[15:54:30] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[15:54:31] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Exception stopping the server
java.lang.NoClassDefFoundError: info/loenwind/autosave/Writer
	at crazypants.enderio.base.TileEntityEio.writeCustomNBT(TileEntityEio.java:104) ~[TileEntityEio.class:?]
	at crazypants.enderio.base.TileEntityEio.writeCustomNBT(TileEntityEio.java:99) ~[TileEntityEio.class:?]
	at com.enderio.core.common.TileEntityBase.writeToNBT(TileEntityBase.java:90) ~[TileEntityBase.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:383) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:174) ~[aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunkData(ChunkProviderServer.java:202) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:230) ~[on.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:4283) ~[oo.class:?]
	at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:574) ~[WorldManager.class:1.12.2-2838-7.1.7-RC3928]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:4656) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:7935) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: info.loenwind.autosave.Writer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 13 more
Caused by: java.lang.SecurityException: class "info.loenwind.autosave.Writer"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_232]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_232]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_232]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_232]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 13 more
[15:54:31] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Shutdown initiated...
[15:54:31] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Shutdown completed.
[15:54:31] [Server thread/INFO] [nucleus]: Nucleus is performing server shutdown tasks.
[15:54:31] [Server thread/INFO] [Actually Additions]: Unloaded WorldData!
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -20
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -21
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -15
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -22
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -13
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -18
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -19
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -16
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -17
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1505
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1503
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1501
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1506
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1511
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1500
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1509
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1502
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1507
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1508
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1510
[15:54:31] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -1504
[15:54:31] [Server thread/INFO] [nuclearcraft]: Server Closing...
[15:54:31] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTED and forced into state SERVER_STOPPED. Errors may have been discarded.
```

**Comment by Rsl1122** [comment]
> Caused by: java.lang.SecurityException: class "info.loenwind.autosave.Writer"'s signer information does not match signer information of other classes in the same package

This exception is not caused by Plan.

See #1291 for alternative solution for the crash

**Comment by Rsl1122** [comment]
I searched for the error on Sponge discord and `java.lang.SecurityException: class signer information does not match signer information of other classes in the same package` occurs when one jar contains source files from two different jars - which is what Mixins do (I have no idea how that works), as some Mixins (apparently) place their content inside the main Sponge jar.

Please try reporting this error to either ImmersiveEngineering or SpongeForge - I don't understand enough about the modding system of Forge to help with this issue. Also check that your Mixins are compatible with the SpongeForge version you're using (You might need to replace the sponge jar with a fresh one when removing mixins, dunno)

**Comment by database64128** [comment]
Thanks for the heads up! Turns out SpongeForge is not the only mod with mixins built in. VanillaFix, LagGoggles, EnderCore all have different mixins applied as different patches. I'm not sure which one caused the issue. But I'll test build 367 to see if things work.

**Comment by database64128** [comment]
I accepted GeoLite2 EULA in the Plan config and updated Plan to build 367, SpongeForge to 7.1.9 RC3986. No issues so far.
